#ifndef MACROS_HEADER
#define MACROS_HEADER

#include <cmath>

#define MAX_FRAGLENGTH 1000
#define MAX_QUEUE_SIZE 20
//#define READ_LEN 100
#define MAXNUM 100000

// #define FRAGMENT_END_DIST 404 + READ_LEN
// #define FRAGMENT_START_DIST 53 + READ_LEN
// #define FRAGMENT_RANGE (FRAGMENT_END_DIST - FRAGMENT_START_DIST)


//#define CB_LENGTH 16
//#define UMI_LENGTH 10
//#define POOL_SIZE std::pow(4, UMI_LENGTH)
#define TENX_WHITELIST_LENGTH 737280

#endif // MACROS_HEADER
